### ISSUE TITLE
Importing `torch` breaks `mitsuba`/`drjit` (again)

### ISSUE THREAD

**Issue by maxfrei750** [mitsuba-renderer/drjit#73]
Since #62 has been merged, importing `torch` breaks `mitsuba`/`drjit`
```
# isort: off
import torch
import mitsuba as mi
import drjit as dr
# isort: on

print(dr.sum([1, 2, 3]))
mi.set_variant("llvm_ad_rgb")

test_scene = mi.load_file("./tests/fixtures/scenes/cbox.xml", res=128, integrator="prb")
print("Success")
```

I encountered this problem before (see https://github.com/mitsuba-renderer/drjit/pull/62#issuecomment-1227654643), but there existed a workaround, i.e. importing `torch` first. Unfortunately, this no longer works (at least for me).

@Speierers Can you reproduce this?

**Comment by Speierers** [comment]
Hi @maxfrei750 ,

I can't reproduce this on my side. Could you try to compile in Debug mode and run this in the debugger maybe?

Also could you remind me your system's specifications, pytorch versions, ...?

**Comment by maxfrei750** [comment]
> I can't reproduce this on my side. 

Interesting. Thanks for trying so quickly.

## Specs

### Host
GPU: RTX 3090
Driver: 515.65.01

### Docker container
OS: Ubuntu 20.04
CUDA: 11.3
Python: 3.8
Torch: 1.12.1+cu113
mitsuba: master 
drjit: master
compiler: clang10

> Could you try to compile in Debug mode and run this in the debugger maybe?

I'll try to find the time today. Unfortunately, I'm not too familiar with C++, so that I might need some help with the debugging.

**Comment by maxfrei750** [comment]
I compiled `mitsuba` in debug mode and now the code from my first post gives me the following messages:

```
6
2022-09-07 11:59:03 INFO  main  [xml.cpp:1413] Loading XML file "./tests/fixtures/scenes/cbox.xml" with variant "llvm_ad_rgb"..
2022-09-07 11:59:03 DEBUG main  [PluginManager] Loading plugin "plugins/srgb.so" ..
2022-09-07 11:59:03 DEBUG main  [PluginManager] Loading plugin "plugins/srgb_d65.so" ..
2022-09-07 11:59:03 DEBUG main  [PluginManager] Loading plugin "plugins/independent.so" ..
2022-09-07 11:59:03 DEBUG main  [PluginManager] Loading plugin "plugins/tent.so" ..
2022-09-07 11:59:03 DEBUG main  [PluginManager] Loading plugin "plugins/hdrfilm.so" ..
Segmentation fault (core dumped)
```

**Comment by maxfrei750** [comment]
Using `gdb -ex r --args python development/mwe.py`, with `mwe.py` being the script from the first post, I get:

```
Reading symbols from python...
Reading symbols from /usr/lib/debug/.build-id/d5/41b4abbfb2556074bfe748118c9c8d3e34af0b.debug...
Starting program: /usr/bin/python development/mwe.py
warning: Error disabling address space randomization: Operation not permitted
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[Detaching after fork from child process 602]
[New Thread 0x7f7c084e6700 (LWP 603)]
[New Thread 0x7f7c07ce5700 (LWP 604)]
[New Thread 0x7f7c034e4700 (LWP 605)]
[New Thread 0x7f7c00ce3700 (LWP 606)]
[New Thread 0x7f7bfe4e2700 (LWP 607)]
[New Thread 0x7f7bfbce1700 (LWP 608)]
[New Thread 0x7f7bfb4e0700 (LWP 609)]
[New Thread 0x7f7bf6cdf700 (LWP 610)]
[New Thread 0x7f7bf44de700 (LWP 611)]
[New Thread 0x7f7bf1cdd700 (LWP 612)]
[New Thread 0x7f7bef4dc700 (LWP 613)]
[New Thread 0x7f7beccdb700 (LWP 614)]
[New Thread 0x7f7bec4da700 (LWP 615)]
[New Thread 0x7f7be7cd9700 (LWP 616)]
[New Thread 0x7f7be54d8700 (LWP 617)]
[New Thread 0x7f7be4cd7700 (LWP 618)]
[New Thread 0x7f7be04d6700 (LWP 619)]
[New Thread 0x7f7bddcd5700 (LWP 620)]
[New Thread 0x7f7bdb4d4700 (LWP 621)]
[New Thread 0x7f7bd8cd3700 (LWP 622)]
[New Thread 0x7f7bd64d2700 (LWP 623)]
[New Thread 0x7f7bd3cd1700 (LWP 624)]
[New Thread 0x7f7bd14d0700 (LWP 625)]
[New Thread 0x7f7bca7f0700 (LWP 626)]
6
[New Thread 0x7f7bc8a88700 (LWP 627)]
[New Thread 0x7f7bb7828700 (LWP 628)]
[New Thread 0x7f7bb7027700 (LWP 629)]
[Thread 0x7f7bca7f0700 (LWP 626) exited]
2022-09-07 14:31:40 INFO  main  [xml.cpp:1413] Loading XML file "./tests/fixtures/scenes/cbox.xml" with variant "llvm_ad_rgb"..
2022-09-07 14:31:40 DEBUG main  [PluginManager] Loading plugin "plugins/srgb.so" ..
2022-09-07 14:31:40 DEBUG main  [PluginManager] Loading plugin "plugins/srgb_d65.so" ..
2022-09-07 14:31:40 DEBUG main  [PluginManager] Loading plugin "plugins/independent.so" ..
2022-09-07 14:31:40 DEBUG main  [PluginManager] Loading plugin "plugins/tent.so" ..
2022-09-07 14:31:40 DEBUG main  [PluginManager] Loading plugin "plugins/hdrfilm.so" ..
--Type <RET> for more, q to quit, c to continue without paging--

Thread 1 "python" received signal SIGSEGV, Segmentation fault.
0x00007f7bca829a00 in ?? () from /lib/x86_64-linux-gnu/libc++abi.so.1
```

**Comment by maxfrei750** [comment]
> Also could you remind me your system's specifications, pytorch versions, ...?

We can also try the other way round: What versions do you use?

**Comment by maxfrei750** [comment]
FYI: Upgrading to CUDA 11.6 did _not_ help.

**Comment by maxfrei750** [comment]
Here you go: :smile: 
```
(gdb) bt
#0  0x00007fbb26c53a00 in ?? () from /lib/x86_64-linux-gnu/libc++abi.so.1
#1  0x00007fbbbb75fe48 in __dynamic_cast () from /lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x00007fbb2584d9cc in mitsuba::Film<drjit::DiffArray<drjit::LLVMArray<float> >, mitsuba::Color<drjit::DiffArray<drjit::LLVMArray<float> >, 3ul> >::Film (this=0x566e4f0, props=...) at ../src/render/film.cpp:36
#3  0x00007fbb24034c36 in mitsuba::HDRFilm<drjit::DiffArray<drjit::LLVMArray<float> >, mitsuba::Color<drjit::DiffArray<drjit::LLVMArray<float> >, 3ul> >::HDRFilm (this=0x566e4f0, props=...) at ../src/films/hdrfilm.cpp:132
#4  0x00007fbb240541f4 in mitsuba::detail::get_construct_functor<mitsuba::HDRFilm<drjit::DiffArray<drjit::LLVMArray<float> >, mitsuba::Color<drjit::DiffArray<drjit::LLVMArray<float> >, 3ul> >, 0>()::{lambda(mitsuba::Properties const&)#1}::operator()(mitsuba::Properties const&) const (this=0x5677db8, p=...) at ../include/mitsuba/core/class.h:224
#5  0x00007fbb240541a2 in std::__1::__invoke<mitsuba::detail::get_construct_functor<mitsuba::HDRFilm<drjit::DiffArray<drjit::LLVMArray<float> >, mitsuba::Color<drjit::DiffArray<drjit::LLVMArray<float> >, 3ul> >, 0>()::{lambda(mitsuba::Properties const&)#1}&, mitsuba::Properties const&> (__f=..., __args=...) at /usr/lib/llvm-10/bin/../include/c++/v1/type_traits:3539
#6  0x00007fbb24054142 in std::__1::__invoke_void_return_wrapper<mitsuba::Object*>::__call<mitsuba::detail::get_construct_functor<mitsuba::HDRFilm<drjit::DiffArray<drjit::LLVMArray<float> >, mitsuba::Color<drjit::DiffArray<drjit::LLVMArray<float> >, 3ul> >, 0>()::{lambda(mitsuba::Properties const&)#1}&, mitsuba::Properties const&>(mitsuba::detail::get_construct_functor<mitsuba::HDRFilm<drjit::DiffArray<drjit::LLVMArray<float> >, mitsuba::Color<drjit::DiffArray<drjit::LLVMArray<float> >, 3ul> >, 0>()::{lambda(mitsuba::Properties const&)#1}&, mitsuba::Properties const&) (__args=..., __args=...) at /usr/lib/llvm-10/bin/../include/c++/v1/__functional_base:317
#7  0x00007fbb24054102 in std::__1::__function::__alloc_func<mitsuba::detail::get_construct_functor<mitsuba::HDRFilm<drjit::DiffArray<drjit::LLVMArray<float> >, mitsuba::Color<drjit::DiffArray<drjit::LLVMArray<float> >, 3ul> >, 0>()::{lambda(mitsuba::Properties const&)#1}, std::__1::allocator<{lambda(mitsuba::Properties const&)#1}>, mitsuba::Object* (mitsuba::Properties const&)>::operator()(mitsuba::Properties const&) (this=0x5677db8, 
    __arg=...) at /usr/lib/llvm-10/bin/../include/c++/v1/functional:1540
#8  0x00007fbb24053263 in std::__1::__function::__func<mitsuba::detail::get_construct_functor<mitsuba::HDRFilm<drjit::DiffArray<drjit::LLVMArray<float> >, mitsuba::Color<drjit::DiffArray<drjit::LLVMArray<float> >, 3ul> >, 0>()::{lambda(mitsuba::Properties const&)#1}, std::__1::allocator<{lambda(mitsuba::Properties const&)#1}>, mitsuba::Object* (mitsuba::Properties const&)>::operator()(mitsuba::Properties const&) (this=0x5677db0, __arg=...)
    at /usr/lib/llvm-10/bin/../include/c++/v1/functional:1714
#9  0x00007fbb257982fd in std::__1::__function::__value_func<mitsuba::Object* (mitsuba::Properties const&)>::operator()(mitsuba::Properties const&) const (this=0x5677db0, __args=...)
    at /usr/lib/llvm-10/bin/../include/c++/v1/functional:1867
#10 0x00007fbb25796559 in std::__1::function<mitsuba::Object* (mitsuba::Properties const&)>::operator()(mitsuba::Properties const&) const (this=0x5677db0, __arg=...)
    at /usr/lib/llvm-10/bin/../include/c++/v1/functional:2473
#11 0x00007fbb257964ee in mitsuba::Class::construct (this=0x5677d40, props=...) at ../src/core/class.cpp:99
#12 0x00007fbb257abaa7 in mitsuba::PluginManager::create_object (this=0x53fdf60, props=..., class_=0x5416a60) at ../src/core/plugin.cpp:180
#13 0x00007fbb2582f67d in mitsuba::xml::detail::instantiate_node(mitsuba::xml::detail::XMLParseContext&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, mitsuba::ThreadEnvironment&, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, Task*, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >--Type <RET> for more, q to quit, c to continue without paging--
 >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, Task*> > >&, bool)::$_4::operator()() const (this=0x7fff2f29ef90) at ../src/core/xml.cpp:1118
#14 0x00007fbb2582e742 in mitsuba::xml::detail::instantiate_node (ctx=..., id=..., env=..., task_map=..., top_node=false) at ../src/core/xml.cpp:1179
#15 0x00007fbb2582e422 in mitsuba::xml::detail::instantiate_node (ctx=..., id=..., env=..., task_map=..., top_node=false) at ../src/core/xml.cpp:1078
#16 0x00007fbb2582e422 in mitsuba::xml::detail::instantiate_node (ctx=..., id=..., env=..., task_map=..., top_node=true) at ../src/core/xml.cpp:1078
#17 0x00007fbb25815efd in mitsuba::xml::detail::instantiate_top_node (ctx=..., id=...) at ../src/core/xml.cpp:1188
#18 0x00007fbb2581634b in mitsuba::xml::load_file (filename=..., variant=..., param=..., write_update=false, parallel=false) at ../src/core/xml.cpp:1425
#19 0x00007fbb1ad955a4 in python_export_xml(pybind11::module_&)::$_0::operator()(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, bool, pybind11::kwargs) const (
    this=0x55b6b68, name=..., update_scene=false, parallel=false, kwargs=...) at ../src/core/python/xml_v.cpp:55
#20 0x00007fbb1ad951d4 in pybind11::detail::argument_loader<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, bool, pybind11::kwargs>::call_impl<pybind11::object, python_export_xml(pybind11::module_&)::$_0&, 0ul, 1ul, 2ul, 3ul, pybind11::detail::void_type>(python_export_xml(pybind11::module_&)::$_0&, std::__1::integer_sequence<unsigned long, 0ul, 1ul, 2ul, 3ul>, pybind11::detail::void_type&&) && (this=0x7fff2f29fc90, f=...) at ../ext/pybind11/include/pybind11/cast.h:1227
#21 0x00007fbb1ad950cf in pybind11::detail::argument_loader<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, bool, pybind11::kwargs>::call<pybind11::object, pybind11::detail::void_type, python_export_xml(pybind11::module_&)::$_0&> (this=0x7fff2f29fc90, f=...) at ../ext/pybind11/include/pybind11/cast.h:1199
#22 0x00007fbb1ad94fc1 in pybind11::cpp_function::initialize<python_export_xml(pybind11::module_&)::$_0, pybind11::object, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, bool, pybind11::kwargs, pybind11::name, pybind11::scope, pybind11::sibling, pybind11::arg, pybind11::arg_v, pybind11::arg_v, char const*>(python_export_xml(pybind11::module_&)::$_0&&, pybind11::object (*)(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, bool, pybind11::kwargs), pybind11::name const&, pybind11::scope const&, pybind11::sibling const&, pybind11::arg const&, pybind11::arg_v const&, pybind11::arg_v const&, char const* const&)::{lambda(pybind11::detail::function_call&)#1}::operator()(pybind11::detail::function_call&) const (this=0x7fff2f2a0378, call=...)
    at ../ext/pybind11/include/pybind11/pybind11.h:232
#23 0x00007fbb1ad94ec5 in pybind11::cpp_function::initialize<python_export_xml(pybind11::module_&)::$_0, pybind11::object, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, bool, pybind11::kwargs, pybind11::name, pybind11::scope, pybind11::sibling, pybind11::arg, pybind11::arg_v, pybind11::arg_v, char const*>(python_export_xml(pybind11::module_&)::$_0&&, pybind11::object (*)(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, bool, pybind11::kwargs), pybind11::name const&, pybind11::scope const&, pybind11::sibling const&, pybind11::arg const&, pybind11::arg_v const&, pybind11::arg_v const&, char const* const&)::{lambda(pybind11::detail::function_call&)#1}::__invoke(pybind11::detail::function_call&) (call=...) at ../ext/pybind11/include/pybind11/pybind11.h:209
#24 0x00007fbb1a50c2a0 in pybind11::cpp_function::dispatcher (self=<PyCapsule at remote 0x7fbb241cac60>, args_in=('./tests/fixtures/scenes/cbox.xml',), kwargs_in={'res': 128, 'integrator': 'prb'})
    at ../ext/pybind11/include/pybind11/pybind11.h:813
--Type <RET> for more, q to quit, c to continue without paging--
#25 0x00000000005f6929 in cfunction_call_varargs (kwargs=<optimized out>, args=<optimized out>, func=<built-in method load_file of PyCapsule object at remote 0x7fbb241cac60>) at ../Objects/call.c:773
#26 PyCFunction_Call (func=<built-in method load_file of PyCapsule object at remote 0x7fbb241cac60>, args=<optimized out>, kwargs=<optimized out>) at ../Objects/call.c:773
#27 0x00000000005f74f6 in _PyObject_MakeTpCall (callable=<built-in method load_file of PyCapsule object at remote 0x7fbb241cac60>, args=<optimized out>, nargs=<optimized out>, keywords=<optimized out>)
    at ../Include/internal/pycore_pyerrors.h:13
#28 0x000000000057164c in _PyObject_Vectorcall (kwnames=('res', 'integrator'), nargsf=<optimized out>, args=<optimized out>, callable=<built-in method load_file of PyCapsule object at remote 0x7fbb241cac60>)
    at ../Include/cpython/abstract.h:125
#29 _PyObject_Vectorcall (kwnames=('res', 'integrator'), nargsf=<optimized out>, args=<optimized out>, callable=<built-in method load_file of PyCapsule object at remote 0x7fbb241cac60>) at ../Include/cpython/abstract.h:115
#30 call_function (kwnames=('res', 'integrator'), oparg=<optimized out>, pp_stack=<synthetic pointer>, tstate=<optimized out>) at ../Python/ceval.c:4963
#31 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at ../Python/ceval.c:3515
#32 0x0000000000569dba in PyEval_EvalFrameEx (throwflag=0, f=Frame 0x7fbbd4343640, for file development/mwe.py, line 10, in <module> ()) at ../Python/ceval.c:741
#33 _PyEval_EvalCodeWithName (_co=<optimized out>, globals=<optimized out>, locals=<optimized out>, args=<optimized out>, argcount=<optimized out>, kwnames=<optimized out>, kwargs=0x0, kwcount=<optimized out>, kwstep=2, 
    defs=0x0, defcount=0, kwdefs=0x0, closure=0x0, name=0x0, qualname=0x0) at ../Python/ceval.c:4298
#34 0x00000000006902a7 in PyEval_EvalCodeEx (closure=0x0, kwdefs=0x0, defcount=0, defs=0x0, kwcount=0, kws=0x0, argcount=0, args=0x0, locals=<optimized out>, globals=<optimized out>, _co=<optimized out>)
    at ../Python/ceval.c:4327
#35 PyEval_EvalCode (co=<optimized out>, globals=<optimized out>, locals=<optimized out>) at ../Python/ceval.c:718
#36 0x000000000067f951 in run_eval_code_obj (co=0x7fbbd42a8660, 
    globals={'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <SourceFileLoader(name='__main__', path='development/mwe.py') at remote 0x7fbbd43f44f0>, '__spec__': None, '__annotations__': {}, '__builtins__': <module at remote 0x7fbbd43ce0e0>, '__file__': 'development/mwe.py', '__cached__': None, 'torch': <module at remote 0x7fbbd4237310>, 'mi': <MitsubaModule(__name__='mitsuba', __doc__=None, __package__='mitsuba', __loader__=None, __spec__=<ModuleSpec(name='mitsuba', loader=None, origin=None, loader_state=None, submodule_search_locations=None, _set_fileattr=False, _cached=None) at remote 0x7fbb24330790>, __path__=['/src/mitsuba3/build/python/mitsuba', '/src/mitsuba3/build/python/mitsuba/python'], __file__='/src/mitsuba3/build/python/mitsuba/__init__.py', _submodule=None, python=<module at remote 0x7fbb24339310>, mitsuba_ext=<module at remote 0x7fbb242ff130>, mitsuba_llvm_ad_rgb_ext=<module at remote 0x7fbb242ff270>, ad=<module at remote 0x7fbbd4237860>) at remote 0x7fbb24336c20>, 'dr': <module...(truncated), 
    locals={'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <SourceFileLoader(name='__main__', path='development/mwe.py') at remote 0x7fbbd43f44f0>, '__spec__': None, '__annotations__': {}, '__builtins__': <module at remote 0x7fbbd43ce0e0>, '__file__': 'development/mwe.py', '__cached__': None, 'torch': <module at remote 0x7fbbd4237310>, 'mi': <MitsubaModule(__name__='mitsuba', __doc__=None, __package__='mitsuba', __loader__=None, __spec__=<ModuleSpec(name='mitsuba', loader=None, origin=None, loader_state=None, submodule_search_locations=None, _set_fileattr=False, _cached=None) at remote 0x7fbb24330790>, __path__=['/src/mitsuba3/build/python/mitsuba', '/src/mitsuba3/build/python/mitsuba/python'], __file__='/src/mitsuba3/build/python/mitsuba/__init__.py', _submodule=None, python=<module at remote 0x7fbb24339310>, mitsuba_ext=<module at remote 0x7fbb242ff--Type <RET> for more, q to quit, c to continue without paging--
130>, mitsuba_llvm_ad_rgb_ext=<module at remote 0x7fbb242ff270>, ad=<module at remote 0x7fbbd4237860>) at remote 0x7fbb24336c20>, 'dr': <module...(truncated)) at ../Python/pythonrun.c:1166
#37 0x000000000067f9cf in run_mod (mod=<optimized out>, filename=<optimized out>, 
    globals={'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <SourceFileLoader(name='__main__', path='development/mwe.py') at remote 0x7fbbd43f44f0>, '__spec__': None, '__annotations__': {}, '__builtins__': <module at remote 0x7fbbd43ce0e0>, '__file__': 'development/mwe.py', '__cached__': None, 'torch': <module at remote 0x7fbbd4237310>, 'mi': <MitsubaModule(__name__='mitsuba', __doc__=None, __package__='mitsuba', __loader__=None, __spec__=<ModuleSpec(name='mitsuba', loader=None, origin=None, loader_state=None, submodule_search_locations=None, _set_fileattr=False, _cached=None) at remote 0x7fbb24330790>, __path__=['/src/mitsuba3/build/python/mitsuba', '/src/mitsuba3/build/python/mitsuba/python'], __file__='/src/mitsuba3/build/python/mitsuba/__init__.py', _submodule=None, python=<module at remote 0x7fbb24339310>, mitsuba_ext=<module at remote 0x7fbb242ff130>, mitsuba_llvm_ad_rgb_ext=<module at remote 0x7fbb242ff270>, ad=<module at remote 0x7fbbd4237860>) at remote 0x7fbb24336c20>, 'dr': <module...(truncated), 
    locals={'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <SourceFileLoader(name='__main__', path='development/mwe.py') at remote 0x7fbbd43f44f0>, '__spec__': None, '__annotations__': {}, '__builtins__': <module at remote 0x7fbbd43ce0e0>, '__file__': 'development/mwe.py', '__cached__': None, 'torch': <module at remote 0x7fbbd4237310>, 'mi': <MitsubaModule(__name__='mitsuba', __doc__=None, __package__='mitsuba', __loader__=None, __spec__=<ModuleSpec(name='mitsuba', loader=None, origin=None, loader_state=None, submodule_search_locations=None, _set_fileattr=False, _cached=None) at remote 0x7fbb24330790>, __path__=['/src/mitsuba3/build/python/mitsuba', '/src/mitsuba3/build/python/mitsuba/python'], __file__='/src/mitsuba3/build/python/mitsuba/__init__.py', _submodule=None, python=<module at remote 0x7fbb24339310>, mitsuba_ext=<module at remote 0x7fbb242ff130>, mitsuba_llvm_ad_rgb_ext=<module at remote 0x7fbb242ff270>, ad=<module at remote 0x7fbbd4237860>) at remote 0x7fbb24336c20>, 'dr': <module...(truncated), flags=<optimized out>, arena=<optimized out>)
    at ../Python/pythonrun.c:1188
#38 0x000000000067fa71 in pyrun_file (fp=fp@entry=0x1db8430, filename=filename@entry='development/mwe.py', start=start@entry=257, 
    globals=globals@entry={'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <SourceFileLoader(name='__main__', path='development/mwe.py') at remote 0x7fbbd43f44f0>, '__spec__': None, '__annotations__': {}, '__builtins__': <module at remote 0x7fbbd43ce0e0>, '__file__': 'development/mwe.py', '__cached__': None, 'torch': <module at remote 0x7fbbd4237310>, 'mi': <MitsubaModule(__name__='mitsuba', __doc__=None, __package__='mitsuba', __loader__=None, __spec__=<ModuleSpec(name='mitsuba', loader=None, origin=None, loader_state=None, submodule_search_locations=None, _set_fileattr=False, _cached=None) at remote 0x7fbb24330790>, __path__=['/src/mitsuba3/build/python/mitsuba', '/src/mitsuba3/build/python/mitsuba/python'], __file__='/src/mitsuba3/build/python/mitsuba/__init__.py', _submodule=None, python=<module at remote 0x7fbb24339310>, mitsuba_ext=<module at remote 0x7fbb242ff130>, mitsuba_llvm_ad_rgb_ext=<module at remote 0x7fbb242ff270>, ad=<module at remote 0x7fbbd4237860>) at remote 0x7fbb24336c20>, 'dr': <module...(truncated), 
    locals=locals@entry={'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <SourceFileLoader(name='__main__', path='development/mwe.py') at remote 0x7fbbd43f44f0>, '__spec__': None, '__annotations__': {}, '__builtins__': <module at remote 0x7fbbd43ce0e0>, '__file__': 'development/mwe.py', '__cached__': None, 'torch': <module at remote 0x7fbbd4237310>, 'mi': <MitsubaModule(__name__='mitsuba', __doc__=None, __package__='mitsuba', __loader__=None, __spec__=<ModuleSpec(name='mitsuba', loader=None, origin=None, loader_state=None, submodule_search_locations=None, _set_fileattr=False, _cached=None) at remote 0x7fbb24330790>, __path__=['/src/mitsuba3/build/python/mitsuba', '/src/mitsuba3/build/python/mitsuba/python'], __file__='/src/mitsuba3/build/python/mitsuba/__init__.py', _submodule=None, python=<module at remote 0x7fbb24339310>, mitsuba_ext=<module at remote 0x7fbb242ff130>, mitsuba_llvm_ad_rgb_ext=<module at remote 0x7fbb242ff270>, ad=<module at remote 0x7fbbd4237860>) at remote 0x7fbb24336c20>, 'dr': <module...(truncated), closeit=closeit@entry=1, flags=0x7fff2f2a08b8)
    at ../Python/pythonrun.c:1085
--Type <RET> for more, q to quit, c to continue without paging--
#39 0x0000000000681b97 in pyrun_simple_file (flags=0x7fff2f2a08b8, closeit=1, filename='development/mwe.py', fp=0x1db8430) at ../Python/pythonrun.c:439
#40 PyRun_SimpleFileExFlags (fp=0x1db8430, filename=<optimized out>, closeit=1, flags=0x7fff2f2a08b8) at ../Python/pythonrun.c:472
#41 0x00000000006b9d32 in pymain_run_file (cf=0x7fff2f2a08b8, config=0x1dba0c0) at ../Modules/main.c:385
#42 pymain_run_python (exitcode=0x7fff2f2a08b0) at ../Modules/main.c:610
#43 Py_RunMain () at ../Modules/main.c:689
#44 0x00000000006ba0bd in Py_BytesMain (argc=<optimized out>, argv=<optimized out>) at ../Modules/main.c:743
#45 0x00007fbbd4668083 in __libc_start_main (main=0x4efd60 <main>, argc=2, argv=0x7fff2f2a0a98, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fff2f2a0a88) at ../csu/libc-start.c:308
#46 0x00000000005fc5fe in _start () at ../Objects/obmalloc.c:1247
```

**Comment by Speierers** [comment]
Ok I can reproduce it now. I will take a look.

**Comment by Speierers** [comment]
Hi @maxfrei750 ,

This should now be fixed. 

DrJit: [8e73de0](https://github.com/mitsuba-renderer/drjit/commit/8e73de015dfcf9fef15b17f7b03717ce90f9ad6c)
Mitsuba: [71ba224](https://github.com/mitsuba-renderer/mitsuba3/commit/71ba224d340e7d718311070c3fc0ceae20234bb6)
