### ISSUE TITLE
Memory leak in PyTorch and Mitsuba interoperability tutorial

### ISSUE THREAD

**Issue by n-kubiak** [mitsuba-renderer/drjit#92]
Hi, I'm having some issues with the [Pytorch-Mitsuba interoperability tutorial](https://mitsuba.readthedocs.io/en/stable/src/inverse_rendering/pytorch_mitsuba_interoperability.html). I'm following the tutorial step by step yet end up with errors. 

If I rescale the textures to something smaller, eg (256,256), I get the below message:
```
Traceback (most recent call last):
  File "bp_playground.py", line 154, in <module>
    loss.backward()
  File "/vol/research/relighting/conda/envs/torch181_cuda111/lib/python3.8/site-packages/torch/tensor.py", line 245, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/vol/research/relighting/conda/envs/torch181_cuda111/lib/python3.8/site-packages/torch/autograd/__init__.py", line 145, in backward
    Variable._execution_engine.run_backward(
RuntimeError: CUDA out of memory. Tried to allocate 16.00 GiB (GPU 0; 23.69 GiB total capacity; 16.00 GiB already allocated; 6.21 GiB free; 16.01 GiB reserved in total by PyTorch)
drjit-autodiff: variable leak detected (5 variables remain in use)!
 - variable a121 (1 references)
 - variable a1 (1 references)
 - variable a9 (1 references)
 - variable a13 (1 references)
 - variable a5 (1 references)
```

If I use a larger image size, eg (1024,1024), the code fails earlier:
```Traceback (most recent call last):
  File "bp_playground.py", line 130, in <module>
    model = Model1()
  File "bp_playground.py", line 119, in __init__
    nn.Linear(res**2, res**2),
  File "/vol/research/relighting/conda/envs/torch181_cuda111/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 79, in __init__
    self.weight = Parameter(torch.Tensor(out_features, in_features))
RuntimeError: [enforce fail at CPUAllocator.cpp:67] . DefaultCPUAllocator: can't allocate memory: you tried to allocate 4398046511104 bytes. Error code 12 (Cannot allocate memory)
```

Do you have any advice? 

Many thanks,
NK

**Comment by Speierers** [comment]
Hi @n-kubiak ,

According to the logs, you are running out of GPU memory while running this tutorial. PyTorch allocates a large chunk of GPU at initialization. You could maybe try to free some of that cache (see [this article](https://pytorch.org/docs/stable/notes/cuda.html#cuda-memory-management))
